name: "Validate"

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Set up node.
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 20.10.0
      - name: Lint
        run: |
          npm ci
          npm run lint
        env:
          CI: true
